# Generated by Django 5.2.6 on 2025-10-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0004_remove_resposta_tag_noticia_tag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_comum',
        ),
    ]
