# Generated by Django 5.2.6 on 2025-11-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0009_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='capa',
            field=models.ImageField(null=True, upload_to='noticias/imagens/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fontes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(null=True, upload_to='noticias/imagens/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tag',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppJCPE.categoria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tag',
            field=models.ManyToManyField(to='AppJCPE.tags'),
        ),
    ]
