# Generated by Django 5.2.5 on 2025-11-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0012_resposta_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='denuncias',
            field=models.IntegerField(default=0),
        ),
    ]
