# Generated by Django 5.2.6 on 2025-09-30 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('materia', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('usuario', models.CharField(max_length=200)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJCPE.noticia')),
            ],
        ),
    ]
