# Generated by Django 5.2.6 on 2025-09-26 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('materia', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em ')),
                ('autor', models.CharField(default='Jornalista', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(verbose_name='Criado em ')),
                ('usuario', models.CharField(default='anônimo', max_length=200)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJCPE.noticia')),
            ],
        ),
    ]
