# Generated by Django 5.2.6 on 2025-09-26 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em '),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em '),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='usuario',
            field=models.CharField(max_length=200),
        ),
    ]
