# Generated by Django 5.2.6 on 2025-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0002_alter_noticia_autor_alter_noticia_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
