# Generated by Django 5.2.6 on 2025-10-16 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0005_delete_usuario_comum'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_filho', to='AppJCPE.resposta'),
        ),
    ]
