# Generated by Django 5.2.6 on 2025-11-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0010_categoria_noticia_capa_noticia_fontes_noticia_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='tag',
            new_name='tags',
        ),
    ]
