# Generated by Django 5.2.5 on 2025-11-11 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0011_rename_tag_noticia_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
