# Generated by Django 5.2.6 on 2025-12-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0015_delete_tag_alter_profile_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to=settings.AUTH_USER_MODEL),
        ),
    ]
