# Generated by Django 5.2.6 on 2025-12-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJCPE', '0016_remove_noticia_autor_noticia_autor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
